import sharp from "sharp"; import fs from "fs";
const idx = JSON.parse(fs.readFileSync("research/projects-index.json", "utf8"));
// curated set (real photos only; no portal watermark, no AI-generated, see research/open-questions.md)
const PICK = [1,2,4,5,6,7,12,13,16,18,19,20,29,35,75,77,78,85,88,90,92,95,96,100,102,103,104,109,110,111,123,129,153,157,158,184,188];
fs.mkdirSync("public/photos", { recursive: true });
const out = {};
for (const k of PICK) {
  const r = idx[k]; const dest = `photos/p${k}.jpg`;
  const m = await sharp(r.file).rotate().resize({ width: 2400, withoutEnlargement: true }).jpeg({ quality: 88, mozjpeg: true }).toFile("public/" + dest);
  out[k] = { src: dest, w: m.width, h: m.height };
}
// brand pics
const brand = { hq: "misc/company-building.png", riyadh: "misc/riyadh.jpg", khobar: "misc/khobar.jpg", hafr: "misc/hafr.jpg", cairo: "misc/cairo.jpg", dubai: "misc/dubai.jpg" };
const b = {};
for (const [n, f] of Object.entries(brand)) { const m = await sharp("public/assets/" + f).jpeg({ quality: 90 }).toFile(`public/photos/${n}.jpg`); b[n] = { src: `photos/${n}.jpg`, w: m.width, h: m.height }; }
fs.writeFileSync("src/generated/photos.ts", `// Auto-generated by scripts/prepare.mjs\nexport type Photo = { src: string; w: number; h: number };\nexport const P: Record<number, Photo> = ${JSON.stringify(out)};\nexport const BRAND = ${JSON.stringify(b)} as const;\n`);
// film grain frames (deterministic noise tiles)
fs.mkdirSync("public/fx", { recursive: true });
for (let i = 0; i < 6; i++) {
  const n = 512, buf = Buffer.alloc(n * n * 4); let s = 1234567 + i * 7919;
  for (let p = 0; p < n * n; p++) { s = (s * 1664525 + 1013904223) >>> 0; const v = (s >>> 24); buf[p*4]=v; buf[p*4+1]=v; buf[p*4+2]=v; buf[p*4+3]=255; }
  await sharp(buf, { raw: { width: n, height: n, channels: 4 } }).png().toFile(`public/fx/grain${i}.png`);
}
console.log("prepared", Object.keys(out).length, "photos");
