import sharp from "sharp"; import potrace from "potrace"; import fs from "fs";
const SRC = "public/assets/logo/logo.jpg";
const GOLD = [0xdc, 0xa5, 0x0d], DARK = [0x38, 0x39, 0x3d];
const { data, info } = await sharp(SRC).removeAlpha().raw().toBuffer({ resolveWithObject: true });
const { width: W, height: H } = info;
const dist = (i, c) => Math.hypot(data[i] - c[0], data[i + 1] - c[1], data[i + 2] - c[2]);
// classify each pixel by nearest of (gold, dark, white) so anti-aliased edges split cleanly
const WHITE = [255, 255, 255];
function mask(target, region) {
  const out = Buffer.alloc(W * H, 255);
  for (let y = region.y0; y < region.y1; y++) for (let x = region.x0; x < region.x1; x++) {
    const i = (y * W + x) * 3;
    const d = [dist(i, GOLD), dist(i, DARK), dist(i, WHITE)];
    const nearest = d.indexOf(Math.min(...d));
    if (nearest === target) out[y * W + x] = 0;
  }
  return out;
}
const layers = {
  markGold: { t: 0, r: { x0: 100, x1: 1140, y0: 250, y1: 1190 }, fill: "#DCA50D" },
  markDark: { t: 1, r: { x0: 100, x1: 1140, y0: 250, y1: 1183 }, fill: "#38393D" },
  baseBar:  { t: 1, r: { x0: 100, x1: 1140, y0: 1183, y1: 1225 }, fill: "#38393D" },
  nameAr:   { t: 1, r: { x0: 100, x1: 1140, y0: 1235, y1: 1320 }, fill: "#38393D" },
  midBar:   { t: 1, r: { x0: 100, x1: 1140, y0: 1322, y1: 1362 }, fill: "#38393D" },
  nameEn:   { t: 0, r: { x0: 100, x1: 1140, y0: 1365, y1: 1440 }, fill: "#DCA50D" },
};
const out = {};
for (const [k, L] of Object.entries(layers)) {
  const buf = await sharp(mask(L.t, L.r), { raw: { width: W, height: H, channels: 1 } }).png().toBuffer();
  const svg = await new Promise((res, rej) => potrace.trace(buf, { turdSize: 8, optTolerance: 0.3, alphaMax: 1.0, blackOnWhite: true, threshold: 128, color: L.fill, background: "transparent" }, (e, s) => e ? rej(e) : res(s)));
  const d = [...svg.matchAll(/ d="([^"]+)"/g)].map(m => m[1]).join(" ");
  out[k] = { d, fill: L.fill, bytes: d.length };
  console.log(k, d.length, "chars");
}
// content bounds
const bounds = { x: 150, y: 285, w: 920, h: 1150 };
fs.writeFileSync("src/generated/logo-paths.ts", `// Auto-generated by scripts/tracelogo.mjs from public/assets/logo/logo.jpg (real brand logo, vector-traced).\nexport const LOGO_VIEWBOX = { x: ${bounds.x}, y: ${bounds.y}, w: ${bounds.w}, h: ${bounds.h} };\nexport const LOGO_COLORS = { gold: "#DCA50D", charcoal: "#38393D" } as const;\nexport const LOGO_LAYERS = ${JSON.stringify(out, null, 1)} as const;\n`);
const full = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${bounds.x} ${bounds.y} ${bounds.w} ${bounds.h}">${Object.values(out).map(l => `<path fill="${l.fill}" fill-rule="evenodd" d="${l.d}"/>`).join("")}</svg>`;
fs.writeFileSync("public/assets/logo/logo-traced.svg", full);
await sharp(Buffer.from(full)).resize({ width: 900 }).flatten({ background: "#ffffff" }).png().toFile("research/logo-traced-preview.png");
